### ISSUE TITLE
Local variable 'annot_gmax' referenced before assignment

### ISSUE THREAD

**Issue by andradekc** [pnucolab/pyoncoprint#10]
Hello,

Thank you very much for developing this package. I'm getting the error **"local variable 'annot_gmax' referenced before assignment"** when running the last piece your example code (plotting step).

Could you please advise?

Thank you very much in advance,
Kelvin

**Comment by pjb7687** [comment]
Hi Kelvin, Thanks for reporting this. The notebook is for the develop version of Pyoncoprint and may not be compatible with it, r vice versa. May I ask if you are running the git version of it?

**Comment by pjb7687** [comment]
I could reproduce it. This happens when your input data does not contain any annotations data. I fixed this in this commit: https://github.com/pnucolab/pyoncoprint/commit/eb71d0ca45ba355d1ee1d0b10d34ecec9268a2af

**Comment by pjb7687** [comment]
Please let me know if you have any further questions!

**Comment by andradekc** [comment]
Sorry for the delayed response. Thank you very much. I really appreciated your attention.
