### ISSUE TITLE
AttributeError: 'GrouperView' object has no attribute 'join'

### ISSUE THREAD

**Issue by lorenzo-C137** [pnucolab/pyoncoprint#13]
I tried to run the example.ipynb with `matplotlib==3.8.3` and when last cell to print and save the plot was run, the following error occurred:

`AttributeError: 'GrouperView' object has no attribute 'join'`

As suggested by a [user](https://stackoverflow.com/questions/77418896/attributeerror-grouperview-object-has-no-attribute-join) downgrading to `matplotlib==3.7.0` solved the error

**Comment by minseo110** [comment]
In 'matplotlib== 3.8.0' and above, modifications to the Groupers returned by the 'get_shared_x_axes' and 'get_shared_y_axes' functions are no longer allowed, which caused the mentioned error.

As of 'pyoncoprint==0.2.5', the package has been updated to be compatible with 'matplotlib==3.8.0' and above.
