### ISSUE TITLE
Change requirements to matplotlib

### ISSUE THREAD

**Issue by fishcakess** [pnucolab/pyoncoprint#15]
Hello :)

May I suggest updating the requirements to be matplotlib 3.6 or 3.7, it seems the newer verisons lose the "join" function which your demo code requires to make the plot.

Best wishes

Liam

**Comment by minseo110** [comment]
Yes, this feature is no longer supported in 'matplotlib==3.8.0' and above.

As of 'pyoncoprint==0.2.5', the package has been updated to be compatible with 'matplotlib==3.8.0' and above.
