### ISSUE TITLE
oncoprint() got an unexpected keyword argument 'is_topplot'

### ISSUE THREAD

**Issue by highwindmx** [pnucolab/pyoncoprint#3]
oncoprint() got an unexpected keyword argument 'is_topplot'

it seems that new version have eliminated this parameter? 3x :)

**Comment by pjb7687** [comment]
Hi, It's still there:
https://github.com/pjb7687/pyoncoprint/blob/master/pyoncoprint/__init__.py#L100

**Comment by highwindmx** [comment]
thanks, I find out pip installed got an obsolete version.
