### ISSUE TITLE
Would you consider adding heatmap annotation plot

### ISSUE THREAD

**Issue by fangyang-cbio** [pnucolab/pyoncoprint#7]
Similar with the zscore heatmap that cbioportal support. Would you consider make it part of pyoncoprint? Thank you!

**Comment by pjb7687** [comment]
Hi @fyfreya, which one do you mean? Can you post a link?

**Comment by afffer** [comment]
![image](https://user-images.githubusercontent.com/110814894/183373116-ee50bebe-4b13-4a09-88f9-ba16c2e767e3.png)
@pjb7687 The part circled by the red box is the heat map that the questioner wants to appear, which is exactly what I need

**Comment by fangyang-cbio** [comment]
> Hi @fyfreya, which one do you mean? Can you post a link?

@afffer has the screenshot! That's exactly what I need. 
And thank you so much for building this python tool!

**Comment by pjb7687** [comment]
Added experimental support in commit 5ca75753f16a767e6374aeef3fac00ee33455084. Could you please give it a try? If it is fine, I will publish it to PyPI.

**Comment by fangyang-cbio** [comment]
Thanks so much on adding this feature! It works great on my local.
Minor thing: I noticed in your `example.ipynb`, the newly added heatmap is off on one side of your plot. Is it a rendering issue? It looks like running on a newer version of python...

**Comment by pjb7687** [comment]
1. Great thanks for reviewing this! Then I am going to publish it to PyPI later today.
2. Thanks for spotting this. It seems to be a rendering issue on Visual Studio Code - it does not happen on a native Jupyter notebook. I will also try to fix it later on.
