### ISSUE TITLE
Continuous clinical information

### ISSUE THREAD

**Issue by afffer** [pnucolab/pyoncoprint#8]
Hi,When the clinical information is continuous, can it be displayed in the form of a bar graph? Similar to the display method in cbioportal?
![image](https://user-images.githubusercontent.com/110814894/183381364-ada1f5e8-32b1-434a-bc23-b987dbaf2b3a.png)

**Comment by pjb7687** [comment]
I've just started working on it together with the heatmap support #7

**Comment by pjb7687** [comment]
Added in commit 56e5ad7a50c4b5dab045bc850c664a5f012b3a63.
